export enum BANK_NAMES {
  HANKOOK = '한국은행',
  KB = 'KB국민은행',
  KU = '기업은행',
  SU = '산업은행',
  WOORI = '우리은행',
  HANA = '하나은행',
  NH = 'NH농협은행',
  JC = '저축은행',
  KBANK = '케이뱅크',
  MGSMGG = 'MG새마을금고',
  KAKAO = '카카오뱅크',
  SHINHAN = '신한은행',
  SCJ = 'SC제일은행',
  WCG = '우체국은행',
  KDB = 'KDB산업은행',
  DG = '대구은행',
  JEJU = '제주은행',
  JB = '전북은행',
  JN = '전남은행',
  GJ = '광주은행',
  BS = '부산은행',
  GN = '경남은행',
  SOOHYUP = '수협은행',
  TOSS = '토스뱅크',
  HKC = '한국씨티은행',
}
